export const sections = [
  {
    id: 'lereng',
    label: 'Lereng',
    eyebrow: 'Babak satu · Tanah',
    title: 'Dari lereng, tumbuh cerita.',
    body: 'Kabut pagi, tanah vulkanik, dan musim yang sabar menumbuhkan karakter pertama di setiap biji.',
    accent: '#D79A3B',
    image: '/assets/scenes/01-lereng.webp',
    start: 0,
    end: 0.2,
  },
  {
    id: 'panen',
    label: 'Panen',
    eyebrow: 'Babak dua · Tangan',
    title: 'Merah yang dipilih satu per satu.',
    body: 'Hanya buah matang yang berpindah ke keranjang—sebuah keputusan kecil yang menjaga rasa tetap utuh.',
    accent: '#B64A36',
    image: '/assets/scenes/02-panen.webp',
    start: 0.2,
    end: 0.4,
  },
  {
    id: 'jemur',
    label: 'Jemur',
    eyebrow: 'Babak tiga · Waktu',
    title: 'Matahari menyimpan manisnya.',
    body: 'Di atas para-para, kopi dibalik perlahan. Angin dan cahaya membangun kejernihan yang akan terasa nanti.',
    accent: '#E9D9B6',
    image: '/assets/scenes/03-jemur.webp',
    start: 0.4,
    end: 0.6,
  },
  {
    id: 'sangrai',
    label: 'Sangrai',
    eyebrow: 'Babak empat · Api',
    title: 'Panas membuka karakternya.',
    body: 'Suhu, suara retak, dan hitungan detik bertemu untuk mengubah potensi menjadi aroma yang nyata.',
    accent: '#C87942',
    image: '/assets/scenes/04-sangrai.webp',
    start: 0.6,
    end: 0.8,
  },
  {
    id: 'seduh',
    label: 'Seduh',
    eyebrow: 'Babak lima · Rasa',
    title: 'Satu cangkir. Seluruh perjalanan.',
    body: 'Yang kamu teguk bukan hanya kopi—melainkan lereng, tangan, waktu, dan api yang tiba di meja yang sama.',
    accent: '#F6F0E4',
    image: '/assets/scenes/05-seduh.webp',
    start: 0.8,
    end: 1,
    cta: 'Jelajahi lagi',
  },
]
